---
- name: Update profile for umask fix
  copy: src=profile.umask-0022 dest=/etc/profile mode=644 owner=root group=root

- name: Copy war app
  copy: src={{ app_name }}-{{ app_version }}.war dest=/home/ec2-user/{{ app_name }}-{{ app_version }}.war mode=664 owner=jboss group=jboss

- name: Deploy app version
  jboss: src=/home/ec2-user/{{ app_name }}-{{ app_version }}.war state=present deployment=webapp.war deploy_path=/usr/share/jboss-as/standalone/deployments/

- name: Update profile for umask fix
  copy: src=profile.umask-0077 dest=/etc/profile mode=644 owner=root group=root
